sudo: false
language: python
os:
  - linux
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox-travis coveralls coverage flake8
script:
  - flake8 .
  - coverage run --source oscheck setup.py test

after_success:
  - coverage report
  - coveralls
